application: knaipa-ua
version: 2
runtime: python
api_version: 1

handlers:

# static handlers such as stylesheets or images

##- url: /stylesheets
##  static_dir: stylesheets
  
# main router script
  
- url: /.*
  script: approuter.py
  